apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: furry-train-web=ghcr.io/shipperizer/furry-train-web-app,furry-train-grpc=ghcr.io/shipperizer/furry-train-grpc-app
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-4148480936
    argocd-image-updater.argoproj.io/furry-train-web.pull-secret: pullsecret:argocd/regcred-github
    argocd-image-updater.argoproj.io/furry-train-web.kustomize.image-name: ghcr.io/shipperizer/furry-train-web-app
    argocd-image-updater.argoproj.io/furry-train-web.allow-tags: regexp:^v[0-9]+.[0-9]+.*
    argocd-image-updater.argoproj.io/furry-train-grpc.pull-secret: pullsecret:argocd/regcred-github
    argocd-image-updater.argoproj.io/furry-train-grpc.kustomize.image-name: ghcr.io/shipperizer/furry-train-grpc-app
    argocd-image-updater.argoproj.io/furry-train-grpc.allow-tags: regexp:^v[0-9]+.[0-9]+.*
  name: furry-train
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/kustomize
    repoURL: git@github.com:shipperizer/furry-train.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
