apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/furry-train-web-app
    sync:
      infer:
      - "cmd/web/main.go"
      - "go.mod"
      - "go.sum"
    custom:
      buildCommand: ./buildx.sh
      dependencies:
        dockerfile:
          path: Dockerfile
  local:
    push: true

deploy:
  kustomize:
    paths:
      - "deployments/kustomize"
      - "argocd-app.yaml"

profiles:
- name: kaniko
  build:
    artifacts:
    - image: ghcr.io/shipperizer/furry-train-web-app
      kaniko:
        image: gcr.io/kaniko-project/executor:arm64
        initImage: docker.io/busybox:stable
    cluster:
      randomDockerConfigSecret: true
      dockerConfig:
        secretName: regcred-github-kaniko
- name: cert-manager
  patches:
    - op: remove
      path: /deploy/kustomize
  deploy:
    kubectl:
      manifests:
        - "deployments/deps/cert-manager/*.yaml"
