apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: test-http-issuer
spec:
  acme:
    email: alexcabb@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-http-issuer-account-key
    solvers:
    - http01:
       ingress:
         class: traefik
