kustomize:
  images:
  - ghcr.io/shipperizer/furry-train-web-app=ghcr.io/shipperizer/furry-train-web-app:v3.1.1
  - ghcr.io/shipperizer/furry-train-grpc-app=ghcr.io/shipperizer/furry-train-grpc-app:v3.1.1-13-g7dff303
