kustomize:
  images:
  - ghcr.io/shipperizer/furry-train-web-app=ghcr.io/shipperizer/furry-train-web-app:v3.2.0
  - ghcr.io/shipperizer/furry-train-grpc-app=ghcr.io/shipperizer/furry-train-grpc-app:v3.2.0
