apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-shipperizer-org
  namespace: default
spec:
  secretName: api-shipperizer-org-tls
  issuerRef:
    name: http-issuer
    kind: ClusterIssuer
  dnsNames:
  - api.shipperizer.org
  duration: 1440h # 60d
  renewBefore: 24h # 1d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
