---
apiVersion: v1
kind: ConfigMap
metadata:
  name: furry-train-web-app
data:
  HTTP_PORT: "8000"
  LOG_LEVEL: ERROR
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: furry-train-grpc-app
data:
  HTTP_PORT: "8000"
  GRPC_PORT: "9000"
  LOG_LEVEL: ERROR
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: furry-train-proxy-app
data:
  HTTP_PORT: "8000"
  GRPC_PORT: "9000"
  LOG_LEVEL: ERROR  