apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: furry-train-web-app
spec:
  routes:
    - conditions:
      - prefix: /api/v0/status
      services:
      - name: furry-train-web-app
        port: 80
