apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  deployment: furry-train-app
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- certificate.yaml
- vservice.yaml
- authzPolicy.yaml
images:
- name: ghcr.io/shipperizer/furry-train-web-app
  newTag: v1.2.0
- name: ghcr.io/shipperizer/furry-train-grpc-app
  newTag: v3.2.0
- name: ghcr.io/shipperizer/furry-train-proxy-app
  newTag: v3.3.0
