apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  deployment: furry-train-web-app
  app: furry-train-web-app
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- certificate.yaml
- httpProxy.yaml
images:
- name: ghcr.io/shipperizer/furry-train-web-app
  newTag: v1.2.0

patchesStrategicMerge:
- rootProxy.yaml
