apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  deployment: furry-train-web-app
  app: furry-train-web-app
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- certificate.yaml
# - rootProxy.yaml
images:
- name: ghcr.io/shipperizer/furry-train-web-app
  newTag: v1.2.0

patchesJson6902:
- target:
    version: v1
    kind: HTTPProxy
    name: api-shipperizer-org
  patch: |
    - op: add
      path: /spec/includes
      value:
      - name: furry-train-web-app
        namespace: default
        conditions:
        - prefix: /api/v0/status
