apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  deployment: furry-train-web-app
  app: furry-train-web-app
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- certificate.yaml
- ingress.yaml
