name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          package-name: furry-train
          pull-request-title-pattern: "[release] chore${scope}: release${component} ${version}."
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build docker image
        run: skaffold build
